PaperMC/docs

- src/css/custom.css
- src/css/index.module.css
- src/pages/index.tsx
serves as a more clear point of access to all docs.
> add large search bar to homepage

- docs/paper/reference/paper-per-world-configuration.md
Removed as of: https://github.com/PaperMC/Paper/pull/7541
> Remove "remove-corrupt-tile-entities" config option

- docs/paper/reference/paper-per-world-configuration.md
Noticed this while researching PaperMC/Paper#7605.
> Document side effect of disable-ice-and-snow

- docs/paper/reference/paper-per-world-configuration.md
This PR aims to add the new entity who can configure the difficulty for break doors, based in the merged PR https://github.com/PaperMC/Paper/pull/6985
> Add new types of entity to door-breaking-difficulty

- docs/paper/reference/paper-per-world-configuration.md
This PR updates the documentation of redstone dust optimizations in accordance with changes made in https://github.com/PaperMC/Paper/pull/7701.
> Update documentation of redstone optimizations

- docs/paper/reference/paper-per-world-configuration.md
https://github.com/PaperMC/Paper/commit/2ab0258b5ab985da6d8fe3728c994b325c08ada0
> Update alt-item-despawn-rate docs

- docs/paper/how-to/anti-xray.md
- docs/paper/how-to/per-world-configuration.md
- docs/paper/reference/paper-global-configuration.md
- docs/paper/reference/paper-per-world-configuration.md
it will take a bit of time to update all of this, going to do the per-world config guide first tomorrow. so for now warn about outdated content on relevant pages
> Warn about currently outdated content for 1.19

- docusaurus.config.ts
Restores functionality of the "edit this page" link.
> Fix edit link

- docs/paper/dev/getting-started/plugin-yml.md
- docs/paper/dev/getting-started/project-setup.md
Addressing the comments from https://github.com/PaperMC/docs/pull/83
> Fixing Comments

- docs/paper/admin/reference/world-configuration.md
https://github.com/PaperMC/Paper/commit/c389b1c4085ab9efc2cfe1714e39c20365d51101
> update reference for configs relying on min/max y levels

- .devcontainer/devcontainer.json
Allows the project to be edited and previewed in a codespace. These are now available for everyone in some capacity, even free accounts.
> chore: DevContainer config for Codespaces

- docs/paper/admin/reference/world-configuration.md
> hide-itemmeta-with-visual-effects docs

- docs/paper/admin/reference/world-configuration.md
> allow-spider-world-border-climbing docs

- docs/velocity/admin/reference/commands.md
The pull request was closed but was manually merged in the commit https://github.com/PaperMC/Velocity/commit/d6c0b71648fa427b1ab036029cfc11223b7496e2
> Document PaperMC/Velocity#786

- docs/paper/admin/reference/world-configuration.md
For https://github.com/PaperMC/Paper/pull/6613
> Update filtering nbt docs

- docs/velocity/dev/api/command.md
I have no idea how I missed this when making the pull request https://github.com/PaperMC/docs/pull/46
> Fixed missing suggestion return on Velocity BrigadierCommand Example

- docs/paper/README.md
> Updated README.md

- docs/paper/admin/getting-started/adding-plugins.md
> feat: add hangar to "Adding Plugins" guide

- docs/velocity/dev/getting-started/creating-your-first-plugin.md
> Remove table imports in `velocity/dev/creating-your-first-plugin`

- docs/paper/admin/how-to/update.md
> Add 'downloads api' link

- docs/paper/dev/api/pdc.md
Upstream recently added the Boolean Persistent Data Type, reflects this in the docs
> Add Boolean PDC Type

- docs/paper/admin/reference/configuration/global-configuration.md
> Fix Description of `compression-format unsupported option`

- CONTRIBUTING.md
Adds a contributing file to outline code quality and also a brief guide on how to add a new page.
> Add A CONTRIBUTING.md

- docs/paper/admin/reference/configuration/global-configuration.mdx
basically mentioning that the components are minimessage formatted
> add message format to the global config

- config/sidebar.paper.ts
- docs/paper/admin/misc/faq.md
- docs/paper/admin/reference/system-properties.md
https://github.com/PaperMC/Paper/pull/9692
> Add faq page and java version check info

- docs/velocity/dev/how-to/plugin-messaging.md
> fix: mention of Paper plugins in Velocity

- config/footer.config.ts
don't you dare steal this @Nacioszeczek
> remove doc link in footer

- docs/paper/admin/reference/configuration/world-configuration.mdx
The default value for this setting has been changed in PaperMC/Paper@6573d9555d80ebe8c70b9c36c4113251055761d3
> Change default value for villager infection chance

- docs/paper/admin/reference/configuration/world-configuration.mdx
See https://github.com/PaperMC/Paper/pull/9895
> Remove Villager Exploit docs

- config/sidebar.misc.ts
- config/sidebar.waterfall.ts
- docs/misc/README.md
- docs/misc/README.mdx
- docs/waterfall/README.mdx
> Rework title pages to use mdx for doc cards

- docs/misc/java-install.md
and signed-by is best practice
> apt-key is deprecated

- config-specs/paper/bukkit.yml
> Document the worlds section of the bukkit.yml

- .github/workflows/format.yml
- .prettierignore
- CONTRIBUTING.md
- package.json
- src/components/ConfigurationStructureDiagram.tsx
Also fixed some weird markup in the contributing file and included it in Prettier's check along with the readme.
> style: add formatting check action and `CONTRIBUTING.md` guideline

- docs/paper/admin/getting-started/migration.md
Improved Migration From CraftBukkit or Spigot  by adding another step
Improved Migration From Vanilla  by adding another step
The step that I added to both tutorials: 
Rename the downloaded file to match the name specified in the start command
> Improved some things to the Migration tutorials and added directory where the two paper configs are

- src/components/Projects.tsx
There may be a better way to do this (Still new to TSX), I recall using some library elsewhere for this, but, probably not worth adding, etc
> Conditionally apply EOL tags

- docs/misc/downloads-api.mdx
> fix: wrong version reference in downloads API example

- config-specs/paper/paper-world-defaults.yml
> Document find-structures-outside-world-border

- config-specs/paper/paper-global.yml
Changed in https://github.com/PaperMC/Paper/commit/59fe7ccc3b067676e5c8b85ccfac915c493f54d9
> Update empty scoreboard team default

- docusaurus.config.ts
- src/util/authorUtils.ts
> fix: ignore untracked file git errors

- docs/misc/downloads-api.mdx
- src/components/StartScriptGenerator.tsx
- the preferred bash is not always at /bin (most modern distros are deprecating non-/usr folders)
- the scripts are posix-compliant and not specifically bash
> fix: correct shebangs

- docs/velocity/admin/reference/commands.md
https://github.com/PaperMC/Velocity/pull/1318/files
> change permission for velocity dump command

- config/sidebar.paper.ts
- docs/paper/dev/api/recipes.mdx
Closes https://github.com/PaperMC/docs/issues/392
> Add recipe documentation

- docs/velocity/dev/getting-started/api-basics.mdx
> fix(velocity/basics): link through to Dependency Management page

- config-specs/paper/paper-global.yml
Document upcoming unsupported option in paper.
See https://github.com/PaperMC/Paper/pull/10877
> Document skip-vanilla-damage-tick-when-shield-blocked

- .github/workflows/deploy-pr.yaml
- .github/workflows/deploy.yaml
> fix(actions): move to different action

- config/footer.config.ts
So currently, when adding the `<Icon>` the text shows up correctly but no icon. Without `<Icon>` the text does not show up correctly and shows on 3 separate lines.
> feat: add current commit to footer

- config-specs/paper/vanilla/paper-world-defaults.yml
Just like its description says, more vanilla!
> Vanilla-like Experience: Set `use-vanilla-world-scoreboard-name-coloring` to true

- docs/paper/dev/api/plugin-messaging.mdx
https://github.com/PaperMC/Velocity/commit/82e81909d8e77f5206a75fa5567cf4b7a7e0b986
> add: KickPlayerRaw

- config-specs/paper/paper-global.yml
- config/sidebar.paper.ts
- docs/paper/admin/how-to/profiling.md
- docs/paper/admin/reference/system-properties.md
- src/components/config/ConfigurationStructureDiagram.tsx
> feat: profiling (spark)

- docs/paper/admin/how-to/profiling.md
~~lets just wait for the action to pass this time @kashike~~
> (hopefully) actually fix link

- config-specs/paper/paper-world-defaults.yml
Closes https://github.com/PaperMC/docs/issues/421
> Document `max-fluid-ticks` and `max-block-ticks`

- config-specs/paper/paper-world-defaults.yml
closes https://github.com/PaperMC/docs/issues/413
> Document Vanilla Interruption bug

- docs/paper/admin/reference/system-properties.md
- pnpm-lock.yaml
Docs PR for https://github.com/PaperMC/Paper/pull/11250
> feat: add docs for symlink validation skipping

- config-specs/paper/paper-global.yml
> Document page-max "disabled" value

- config-specs/paper/paper-global.yml
- docs/paper/admin/reference/system-properties.md
relevant: https://github.com/PaperMC/Paper/blob/83b6b26d39e2fd9f9dfe7713e70cd28f5080b17a/patches/server/0009-MC-Utils.patch#L3679-L3691
> fix: wrong worker thread count description

- config-specs/paper/paper-world-defaults.yml
For https://github.com/PaperMC/Paper/pull/11312
> Add despawn-range-shape to paper world config

- config-specs/paper/paper-world-defaults.yml
> The misc.max-leash-distance is now a DoubleOr.Default

- docs/paper/dev/getting-started/userdev.mdx
Also added some filenames to the codeblocks
> Remove hardcoded userdev version

- docs/paper/admin/reference/system-properties.md
https://github.com/PaperMC/Paper/pull/10127
> feat: Velocity forwarding secret environment variable

- config-specs/paper/paper-world-defaults.yml
- **work**
- **Adopt new layout**
> Document void damage configuration

- config-specs/paper/paper-world-defaults.yml
Docs for https://github.com/PaperMC/Paper/pull/11333
> Add docs for new alternate-current config

- docs/paper/dev/api/commands.mdx
sample code from the Fabric wiki on contextual suggestions doesn't work
> Add command suggestions docs

- config-specs/paper/bukkit.yml
- docs/paper/admin/reference/configuration/README.mdx
> Update config references

- docs/folia/admin/reference/faq.md
https://github.com/PaperMC/Folia/issues/116
> Add restart to disabled folia commands

- config-specs/paper/paper-world-defaults.yml
For https://github.com/PaperMC/Paper/pull/11454
> Docs for entity ttl

- docs/velocity/admin/reference/system-properties.md
add version where strict error handling has been removed
> addition: update support window for strict error handling property

- config-specs/paper/spigot.yml
> Correct value to disable player-shuffle

- docs/paper/dev/api/plugin-messaging.mdx
Base on: https://github.com/PaperMC/Velocity/pull/1484
> feat: add 'GetPlayerServer' message type

- config-specs/paper/paper-world-defaults.yml
Resolve #540
"Thanks" IJ for the style changes i dont request...
> Document old enderpearl behaviour world config

- config-specs/paper/paper-world-defaults.yml
Paper pr reference: https://github.com/PaperMC/Paper/pull/12186
> Document cooldownFailedBeehiveReleases

- config-specs/paper/paper-world-defaults.yml
Paper pr: https://github.com/PaperMC/Paper/pull/12201
> Remove unused light queue size option

- docs/velocity/admin/reference/system-properties.md
add the [`velocity.disable-iouring-transport`](https://github.com/PaperMC/Velocity/blob/a549880df1a7454799d30be57b9b7df4cb5c43b7/proxy/src/main/java/com/velocitypowered/proxy/network/TransportType.java#L119) system property
> chore: update Velocity's system properties

- .typos.toml
- src/content/docs/paper/admin/how-to/basic-troubleshooting.md
This PR expands the troubleshooting guide by adding troubleshooting steps for common issues. Most of the original text was kept intact, however, some parts were moved to different sections.
> Expand troubleshooting guide

- src/content/docs/paper/dev/api/plugin-configs.mdx
- src/content/docs/paper/dev/getting-started/plugin-yml.mdx
This PR just highlight in the FileTree the files mentioned or make more clear.
> style: highlight in FileTree specific files mentioned

- src/content/docs/folia/admin/reference/region-logic.md
to adhere to the third invariant.
> typo: "to adhere to invariant third invariant."

- src/config/paper/paper-global.yml
Documents config value created in https://github.com/PaperMC/Paper/pull/12503
> feat: add xp-merge-percentage config

- src/content/docs/paper/admin/reference/system-properties.md
- src/content/docs/paper/dev/getting-started/paper-plugins.md
- src/content/docs/paper/dev/getting-started/plugin-yml.mdx
Related to https://github.com/PaperMC/Paper/pull/12689.
> feat: document Maven Central mirror settings

- src/content/docs/misc/downloads-api.mdx
- src/utils/versions.ts
Swaps all existing examples to use Fill. 
Also added GraphQL examples for those who may want to use it.
> feat: update docs to fill v3

- src/content/docs/paper/dev/api/particles.mdx
This PR fixes a name mismatch between the Rising particles chapter's name and its list
> Fix name mismatch between rising particles list and chapter
