docs/paper/reference/paper-global-configuration.md
Because the header was set to `##` instead of `###`, some settings were unintentionally added as children of the timings category:
=> Fix header for timings category

config/sidebars.config.ts, docs/paper/getting-started/adding-plugins.md, docs/paper/getting-started/getting-plugins.md
Especially unsure about the `Finding Plugins` section. Do we want to link spigot? I feel like we pretty much have to. I wouldn't be super comfortable including the section at all if it weren't linked, as that would be a pretty significant disservice to people finding plugins.
=> Add Paper Plugin Installation Guide

docs/velocity/developers/api/event.md
Actually the example contradicts itself by saying `You'll notice that your events don't need to extend or implement anything. They just work.` being that the example implements an interface and the `Event` interface never existed and confuses many people thinking that they have to implement this interface
=> Removed Event interface from custom velocity event example

docs/paper/reference/paper-global-configuration.md
It got removed in the Tuinity merge here https://github.com/PaperMC/Paper/commit/7d10cdea0358854138d0d0ada5e74c58c688dea7#diff-cabcb269ec3936b8c8cd99cfe30492bc7aafc3a835fae86fda89b7543bc1d5f4L21
=> Remove chunk-tasks-per-tick

config/navbar.config.ts, config/sidebars.config.ts, docusaurus.config.ts, src/theme/DocBreadcrumbs/index.tsx, src/theme/DocBreadcrumbs/styles.module.css
Fixes an issue @MiniDigger noticed with google crying about invalid breadcrumbs.
This is intentional on the end of Docusaurus, ref https://togithub.com/facebook/docusaurus/pull/6932. Possibly a better solution is just to remove the last breadcrumb. I'm not sure, as there is good rationale provided there.
=> Breadcrumb links to all pages, category indexes

src/css/custom.css
I'm not quite sure I like the look of this right now, especially as it pushes the actual text on the sidebar over a bit. This was to prevent word wrapping changes when selecting a sidebar item. I'm not sure that it's the correct way to do that. There might be something better.
unwanted behaviour:
https://user-images.githubusercontent.com/76139600/172642360-e0221129-5381-4cd4-8d05-74d24e430702.mov
=> Clarify navigation by marking current sidebar page with activity bar

docs/paper/reference/paper-global-configuration.md, docs/paper/reference/paper-per-world-configuration.md
Was missing units (ticks) and had incorrect info about the default behaviour of `player-auto-save-rate`. Admittedly though, the default behaviour does seem weird
=> clarify auto save intervals

config/sidebar.paper.ts, docs/paper/admin/reference/system-properties.md
As outlined: https://github.com/PaperMC/docs/issues/23 the documentation of paper system properties has been widely just cat telling people in paper-help :)
I have omitted some of the properties outlined in those issues as a lot of them were removed in 1.14. The ones removed in the last two versions I have kept. Any more which I have missed or formatting issues let me know
=> Document the paper system properties

config/sidebar.paper.ts, docs/paper/dev/getting-started/plugin-yml.md, docs/paper/dev/getting-started/project-setup.md
Adds a basic project setup for gradle as well as an outline of the `plugin.yml`. Although spigot already has one of these pages, with the potential for specific paper keys with Owen's PR and a hardfork soon, I deemed it proper to have a page here as well.
=> Add a basic development guide

docs/paper/admin/reference/world-configuration.md
This was previously indented one level too few which lead to it being treated as on the same level as the actual parent `spawning` and as the parent section of the following, not directly related keys like `filter-nbt-data-from-spawn-eggs-and-related` or `iron-golems-can-spawn-in-air`.
=> Fix `duplicate-uuid` section indention

docs/paper/admin/reference/world-configuration.md
This PR does two things:
1. Add more explaination about `fix-climbing-bypassing-cramming-rule` config
* I hope this would help people to better understand how this config works
2. Change 'gamerule' to 'game rule'
* This is how client says about it
3. Fix `hidden-blocks` description
* It was broken
=> Add explaination about config & Fix/Modify document

docs/velocity/admin/reference/server-compatibility.md
https://github.com/PaperMC/docs/pull/79: "*There is still no way to automatically update this value through the API as mentioned in the previous pull request*"
https://github.com/PaperMC/Velocity/pull/893 / https://github.com/PaperMC/Velocity/commit/b1fa9dc9538b19f4fe84fd42add212562068a367
=> Update Velocity compatibility to Minecraft 1.19.3

README.md
This PR handle a few things related to the badges in README.
- Removed the build badge because currently this rep not has active workflows.
- Added badge to discord
- Change the environment in the badge of deployment to point to the currently working production
=> [ci skip] Update badges in README

docs/paper/admin/how-to/anti-xray.md
The recommended anti-xray config for the nether was missing the enabled and engine-mode values.
=> Add missing values to nether configuration

docs/paper/admin/how-to/anti-xray.md
This renamed the "Overworld Configuration" to default world since it's no longer the overworld config but a config for all worlds without an override.
=> Change anti-xray world configuration headers

docs/paper/admin/how-to/anti-xray.md
Ensures that a newline at end of file is inserted when people press the copy button and paste into their config files.
=> Add newline at eof in Anti-Xray example configs

docs/paper/admin/how-to/anti-xray.md
Replaces the default `replacement-blocks` list with an empty list `[]` in `engine-mode: 1` to make it clearer that this list isn't used. Also moves up the comment to its appropriate place.
=> Clarify that replacement-blocks list is not used in engine-mode: 1

src/css/custom.css
When in light mode the background color of an alert box does not really stand out like it does in dark mode.
Better light mode background from this PR:
Old light mode:
(Dark mode as reference:
=> Improve warning background color in light mode

config/navbar.config.ts, src/css/custom.css
supersedes #139 
looks like this:
=> fix logo size and alignment

docs/paper/dev/getting-started/plugin-yml.md
- Add `contributors` field
- Add default value of `load`
- Fix format of commands/permissions/children sections. Those need to be config sections, not map lists.
- Mention that permission default values that are not specified will default to the value of `default-permission` (which defaults to `op`)
- Add `default-permission` field
- Add `provides` field
Tbh. it's a bit questionable if this should be documented and maintained again on a separate page seeing as the JavaDocs [already provide a pretty good overview](https://jd.papermc.io/paper/1.19/org/bukkit/plugin/PluginDescriptionFile.html). Maybe that could be auto-generated at some point in the future?
=> Improve plugin.yml documentation

docs/velocity/admin/reference/server-compatibility.md
https://github.com/PaperMC/docs/pull/79: _"There is still no way to automatically update this value through the API as mentioned in the previous pull request"_
=> Update Velocity compatibility to Minecraft 1.19.4

config/navbar.config.ts
Fixed an issue where links to Folia's Development page were not being displayed in the navbar
=> fix: navber fixes

docs/folia/admin/reference/faq.md
Folia disables a handful of commands and currently to see them you have to dig through the patch or code. This'll just list them all out in the FAQ for easier viewing.
=> Add disabled commands to Folia's FAQ

docs/misc/java-install.md
Even though most of these dependencies are shipped with minimal installations of Debian (and even the Ubuntu Docker image), there's been a few reports of them missing on Ubuntu.
=> Add more dependencies to the Java install docs

docs/folia/admin/reference/overview.md
Both teleportation paragraphs were worded in a complicated manner. I hope I understood it right for the rewrite. Particularly I changed this construction (from/to):
> completed by forcing
the entity being teleported to be added to the entity chunk specified
by the target location
> completed by ensuring the addition
of the teleporting entity to the destination chunk specified
by teleporation
There's no "entity chunk" right? It's just a "chunk"
For simple teleportation I changed "forcing" to "ensuring", because the logic (as described) does not change the previous outcome, so it's less in the way of "forcing" and rather "ensuring" it happened. "Forcing" is still used for the Portal TP where it practically cancels, made more clear with "no teleportation"
PS: I had to reflow the Portal …
=> Folia overview.md: rephrase sentences

docs/velocity/admin/reference/commands.md
I was trying to figure out how to disable `/velocity version` for some players and had to [delve into the source code](https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/command/builtin/VelocityCommand.java#L258) to find the permission node. 
This change adds a note that the permission node `velocity.command.info` controls access to the `/velocity version` command.
=> Add permission documentation for /velocity version

docs/paper/admin/reference/configuration/global-configuration.md
The recently merged pull request PaperMC/Paper#9368 allows server owners to disable block updates from affecting note blocks or tripwires, providing an easy way to developers/mapmakers to use them for custom blocks.
This commit provides plain documentation for these two options on the paper documentation page.
=> Document added block update configuration

docs/paper/dev/misc/reading-stacktraces.md
This makes the line-by-line analysis of the stacktrace match the full output above
=> change "null" to "player" in example stacktrace line

docs/paper/admin/reference/configuration/global-configuration.md
Closes #188 by adding some missing nodes
=> Document Missing Configuration Nodes

docs/paper/dev/getting-started/paper-plugins.md
The classloader isolation currently implemented does not prevent non-paper plugins from accessing paper plugins' classloaders. As a result, relocation remains a good practice to prevent conflicts with non-paper plugins.
This PR is far more limited in scope than #183
=> Clarify classloader isolation section on relocation

config/sidebar.paper.ts, docs/paper/dev/getting-started/userdev.md
Partially addresses https://github.com/PaperMC/docs/issues/19
----
First crack at better docs than just linking to the test plugin.
=> Add simple docs for userdev

config/sidebar.paper.ts, docs/paper/dev/api/component-api/i18n.md
part of https://github.com/PaperMC/docs/issues/190
=> Add docs for i18n in paper

docs/paper/admin/reference/configuration/global-configuration.mdx, docs/paper/admin/reference/configuration/server-properties.mdx, docs/paper/admin/reference/configuration/world-configuration.mdx
add the filepath to the paper-config files,
merges file info into the "info" block of server.properties to match paper-global and paper-world
side note: i dont know why idea keeps removing the space, i cannot commit without it disappearing
=> add expected filepaths to config docs

src/components/Config.tsx, src/css/custom.css
This PR adds a button that lets you expand or collapse all the config descriptions at once. I've also taken the liberty of fixing some of the linter warnings I was getting, as well as some weird issues that I ran into while attempting to implement this feature.
I've also attached a `showDescriptions` parameter to the Config component that defaults to `false`. Setting it to `true` will expand all the descriptions initially. It might be useful to show all descriptions for smaller configs by default, since they don't take up as much screen space.
=> add button that expands/collapses all config descriptions

src/components/Config.tsx, src/css/custom.css
This PR replaces the anchor element used for the config nodes with the button element. `clean-btn` and `button--link` are applied to render the button the same as an anchor element, and `config-node` is used for any leftover stylings required to keep visual parity.
https://github.com/PaperMC/docs/assets/43185817/62efe4ca-4f5b-4e59-a836-8655f46ad953
(keystroke visualizer: https://github.com/mulaRahul/keyviz)
Near the end of the video I notice a weird inconsistency with the config descriptions for the `hidden-blocks` and `replacement-blocks` showing incorrectly in production compared to my dev environment. Not sure what's up with that.
=> Make config nodes accessible through keyboard shortcuts

docs/paper/admin/reference/configuration/global-configuration.mdx
This bit used to be commented out, but after the big config revamp the comment part was removed
=> Remove reference to a guide that doesn't exist

docs/velocity/admin/getting-started/forwarding.md
Not *too* sure on the wording, so suggestions welcomed. Disabling online mode in the server.properties is mentioned in the getting started guide at the very bottom, but worth mentioning on this page aswell
do we also want to mention this in the legacy forwarding part?
=> Mention disabling server.props online mode in forwarding guide

docs/paper/admin/reference/configuration/global-configuration.mdx
This adds the necessary description for the new `compression-level` config option in `config/paper-global.yml`
See https://github.com/PaperMC/Paper/pull/9711
=> add compression-level description

docs/misc/java-install.md
I recently heard that Paper recommends 21, the latest Java LTS.
=> Latest Java LTS

docs/paper/dev/getting-started/paper-plugins.md
Noticed that this line
was missing the word `load` between `this plugin should` and `before or after`.
Corrected Version:
=> Adds missing word 'load' in paper-plugins guide

docs/paper/dev/getting-started/userdev.md, docs/paper/dev/misc/internal-code.mdx
Bumped the pw version, fixed a couple typos/grammar issues, and made mentions of `paperweight-userdev` *more* consistently stylized, notable exception is I left the sidebar Title Case since it felt weird with the usual kebab case used by pw. Also added a note about keeping userdev up to date.
=> Minor improvements to internals and userdev pages

docs/velocity/dev/api/command.md
A week ago [new methods were implemented in the Velocity API module](https://github.com/PaperMC/Velocity/pull/1161) that can help to understand more easily the operation of the Brigadier commands especially for those who are just starting with the Velocity API, by avoiding using generics and adding useful checks to avoid beginner mistakes.
I didn't make this pull request earlier because I was waiting for the javadocs to be updated with these changes, which just happened a [few minutes ago](https://discord.com/channels/289587909051416579/908507886420910101/1192999650697937049)
=> Improved Velocity command documentation with newly added API

docs/misc/downloads-api.mdx
fixes #308 
@phant0m2290 if you want me to add you as co-author i would need your commit signature
=> Actually use project variable in download script

src/components/Config.tsx
I have no sane means to test this, but, this *should* tell site translators to not translate certain aspects of the configuration, if we want to go on with this, there's probably several other things we'd want to apply this to, i.e. any cross-refs to the configuration page, for ex
=> Add some notranslate hints

docs/paper/dev/api/pdc.md
The PDC API recently was expanded to cover list types. This commit adds a simple example for developer that either
a) Want to store a list of a custom pdt
b) Want to store a list of strings or other api defined types
The commit also provides a quick example of retrieving the data as the implementation allows fully type-safe access to the data.
Also drops some unneeded spaces at EOL.
=> Add documentation for list persistent data types

config-specs/paper/paper-global.yml, config-specs/paper/server-properties.yml
The ip logging option was implemented by mojang in 1.20.2 and replaced the existing paper configuration option.
This commit properly moves the documentation and name of that option.
=> Move the ip logging configuration reference

docs/paper/admin/getting-started/adding-plugins.md, docs/paper/admin/how-to/update.md
- Added one more step to updating Paper Tutorial.
- Formatted logs in AddingPlugins > Troubleshooting to resemble console output.
- Added a tip for the backup step of the Paper Update tutorial
=> Improved some things to guides

docs/paper/dev/getting-started/userdev.mdx
According to https://plugins.gradle.org/plugin/io.papermc.paperweight.userdev, the latest version is now 1.5.12
This PR is supposed to update that
=> Update userdev version to latest

src/components/StartScriptGenerator.tsx
adds an @echo off in front of all windows scripts and adds a pause statement after if auto restart is disabled. This is because people on windows tend to double click the start.bat instead of opening a terminal and running the script from there, which causes the terminal to close when the server stops without giving the user the option to look at e.g. crash logs, i have noticed a lot of people on the discord server just saying "my server stops without any crash log" because of this exact reason.
=> Improve Start Script Generation for Windows

docs/paper/dev/getting-started/plugin-yml.mdx
Considering that Paper plugins are the new hotness, we should probably distinguish the old Bukkit plugin YMLs from the new paper-plugin.yml, especially considering that a plain 'Plugin YML' page on the 'Paper' site lends itself to assuming 'Paper Plugin YML' is what the page describes, despite that being not the case.
=> Retitle plugin YML page to specifically mention Bukkit

config-specs/paper/server-properties.yml, docs/paper/dev/getting-started/plugin-yml.mdx
For now, I added the 2 new `server.properties` entries and `plugin.yml` now accepts patches in their `api-version` field. Let me know if i missed something.
Blocked until 1.20.5 ready.
=> Document various 1.20.5 config changes

docusaurus.config.ts, src/util/authorUtils.ts
Ignores untracked file errors in more places, apparently didn't see them all before.
=> fix: ignore untracked file errors, attempt 2

config-specs/paper/paper-global.yml, docs/paper/admin/reference/system-properties.md, docs/paper/dev/getting-started/project-setup.mdx, docs/paper/dev/getting-started/userdev.mdx
Add section about plugin remapping and system property to disable it.
Also updated paperweight version to 1.6.2
=> feat: Add info about plugin remapping and update paperweight version.

src/components/StartScriptGenerator.tsx, src/css/start-script-generator.css
Updates Platform SelectMenu to the new version in the script generator.
=> Update Platform Select in Start Script Generator

config/sidebar.paper.ts, docs/paper/dev/api/entity-teleport.mdx, docs/paper/dev/api/roadmap.mdx
=> feat: entity teleportation API

docs/paper/dev/misc/internal-code.mdx
I wasn't sure if I should rewrite rather than only adding admonitions. If I should do it lmk.
=> feat: Add information about 1.20.5 changes to internals to nms guide

docs/paper/dev/api/entity-api/entity-teleport.mdx
=> fix: recommend `teleportAsync` usage over `teleport`

docs/paper/dev/api/commands.mdx
The bootstrap example class was package private in the documentation for paper plugin commands, fixed that
=> fixed classes in command API docs not being public

docs/paper/admin/getting-started/getting-started.mdx, src/components/StartScriptGenerator.tsx
I propose that xmx/xms be reordered here (min memory -> max memory as opposed to max memory -> min memory) which makes the overall readability of the script.
=> Change xmx/xms ordering

docs/paper/dev/getting-started/plugin-yml.mdx
Spigot changed the api version in 1.20.5 and allows minor versions from there on. Since paper adapted this change the docs should reflect this, which they in fact already do. So the documentation is not coherent with the example already.
https://www.spigotmc.org/threads/spigot-bungeecord-1-20-5-1-20-6.645069/#post-4722247
=> Update api-version usage with minor version support.

.github/workflows/deploy-pr.yaml, config-specs/paper/paper-global.yml
example comment 
https://github.com/AdrianGonz97/refined-cf-pages-action/blob/c7b767eef599f127d8ce2388d4ed2270d3b750af/src/comments.ts#L126
=> fix(action): (probably) fix preview action

docs/paper/dev/getting-started/userdev.mdx
When looking through the docs and trying to get the userdev plugin to work I noticed this line being faulty.
This PR updates it to reflect the actual code one has to write.
Based on https://discord.com/channels/289587909051416579/1078993196924813372/1252988263073972294 (Message link in the papermc discord server)
=> Fix: Incorrectly defined task in paper/dev/userdev

.github/workflows/deploy-pr.yaml, .github/workflows/deploy.yaml, docusaurus.config.ts, src/util/pagesUtils.ts
Fixes broken metadata and makes the sitemap generate once again. To me, it seems like there's no way to get a deployment URL at build time, so this PR tries to guess it for previews.
Based on my observations, deployment URLs are formatted in the `https://<id>.papermc-docs.pages.dev` format, where `<id>` is a `<PR head branch owner>-<branch name>` identifier capped to 28 characters and special characters (`/`, `_`, `.`) replaced with a dash.
Examples:
- `https://papermc-feat-add-trial-chamb.papermc-docs.pages.dev`
- `https://zlataovce-fix-highlight-cont.papermc-docs.pages.dev`
- `https://papermc-121.papermc-docs.pages.dev`
=> fix: correct base URL for Pages deployments

config-specs/paper/server-properties.yml, src/components/config/ConfigurationStructureDiagram.tsx
`resource-pack-id` usage found through https://minecraft.wiki/w/Resource_pack and `bug-report-link` usage found through my own testing.
Also corrects the information for the `logs/` directory in the Paper Configuration page component.
Closes #425
=> Update server-properties.yml with new keys and minor correction elsewhere

docs/paper/admin/how-to/anti-xray.mdx
I'm unsure if I've put it in the correct place, but the bypass anti-xray permission node appears to be undocumented
=> document anti-xray bypass permission

config-specs/paper/vanilla/paper-global.yml, config-specs/paper/vanilla/paper-world-defaults.yml, config-specs/paper/vanilla/spigot.yml, config/sidebar.paper.ts, docs/paper/admin/how-to/get-to-vanilla.mdx
This PR aims to set the foundation for the "How to get as close as possible to a vanilla experience" page. 
I took https://github.com/PaperMC/docs/issues/21#issuecomment-1062254884 as a reference for the initial work. Some of the settings listed don't exist anymore. 
I am sure those are not the only ones. Therefore, I would appreciate it if we can find more settings together as it would be a huge effort for one person to go through every setting. 
Ideally, we would add a little text to why these changes have been made and stuff like that. Please provide feedback in this direction. The design is also not final, but I think that would be the logical design choice? With listing every file that contains vanilla breaking changes as separate config.
I also think we should include a link at each …
=> Document vanilla breaking changes

docs/misc/hangar-publishing.md, docs/misc/java-install.md, docs/velocity/admin/getting-started/faq.mdx, docs/velocity/admin/reference/server-compatibility.mdx, docusaurus.config.ts
Since Waterfall went EoL for quite some time now I believe it shouldn't be mentioned in examples/documentations anymore. I also replaced Waterfall->Folia in the main page's description since I think it became more important than Waterfall over time.
=> Remove some Waterfall references

package.json, patches/@docusaurus__theme-common@3.4.0.patch, pnpm-lock.yaml
Makes the search bar display results only from the currently opened project.
This should have no effect on non-project pages, such as the main or search page; results from all projects should still be displayed there.
=> fix: show search results only from the active project

docs/paper/dev/misc/databases.mdx
This PR fixes a mistake made in the JDBC url from the "Using Databases" page on the "Simple MySQL Setup" dropdown.
From ``jdbc://mysql://localhost:3306/mydatabase`` to ``jdbc:mysql://localhost:3306/mydatabase``.
I just removed the two ``//`` after ``jdbc:``, according to the Microsoft documentation [Building the connection URL](https://learn.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver16):
``jdbc:sqlserver://[serverName[\instanceName][:portNumber]][;property=value[;property=value]]``.
=> fix: using-databases jdbc url for mysql

.github/workflows/build-preview.yaml, .github/workflows/deploy-preview.yaml
Hey! I'm the maintainer of the Github Action [refined-cf-pages-action](https://github.com/AdrianGonz97/refined-cf-pages-action) and we were recently made aware of a security vulnerability regarding the `pull_request_target` workflow event where it's possible to leak secrets (including the CF credentials used in the action) through a Github Actions exploit when running untrusted code. Unfortunately, our previous recommendation for the setup of the _PR Previews from Forks_ feature included the use of this workflow event type without PR approvals, which [has now been updated](https://github.com/AdrianGonz97/refined-cf-pages-action#enabling-pr-previews-from-forks). 
I'm going around to all of the dependents of the action that are using the _PR Previews from Forks_ feature to apply the fix. …
=> fix(security): PR Previews from Forks

docs/paper/dev/getting-started/userdev.mdx
When using `paperweight-userdev` with Gradle and Groovy syntax instead of Gradle Kotlin DSL, some modifications to the code described in the documentation are necessary.
I have added a note to the documentation regarding the issues I encountered and how to resolve them.
=> Document methods to resolve issues with Gradle in Groovy

docs/velocity/dev/getting-started/api-basics.mdx
Although the importance is already *considered* by adding it to the "Common Pitfalls", I believe it would help if this is marked as a *warning* to give people a heads-up.
Link to the original page: https://docs.papermc.io/velocity/dev/api-basics#a-word-of-caution
Link to the page: https://timongcraft-feat-velocity-ma.papermc-docs.pages.dev/velocity/dev/api-basics#a-word-of-caution
=> feat: add caution admonition for plugin loading phases in Velocity

config/sidebar.velocity.ts, docs/velocity/admin/reference/system-properties.md
This PR adds a page for Velocity's system properties,
as requested in [Velocity#1404](https://github.com/PaperMC/Velocity/issues/1404#issuecomment-2284748391).
=> Add docs for Velocity's system properties

docs/paper/dev/api/pdc.mdx
Several minor PDC clarifications
- Warning box for developers, clarifying that PDCs must be **manually** copied from holder to holder
- Correction of TileState explanation
- Adding of other PersistentDataHolders
=> PDC Clarifications

config-specs/paper/paper-world-defaults.yml
If auto replenished is enabled, stationary containers can be re-looted. When broken, usually by players, the loot is unpacked and the loottable is destroyed.
The commit expands the wording to also cover shulker boxes, which work a bit differently. In case a player breaks them, they are immediately looted and loose their replenishment ability. In case of a piston breaking them, they cannot unpack their loot table as no player exists in the context, so they only loose their loot table if they have been looted once before.
=> Specify when loottable is removed for replenished

docs/velocity/dev/getting-started/pitfalls.mdx
- Documented support for tablist headers, footers, and resource packs.
- Clarified that unsupported operations include sounds and books. (currently the only unsupported operations)
Support for resource packs was added to the `ConnectedPlayer` class [here](https://github.com/PaperMC/Velocity/commit/cbd07b14349c449202e84a840da1167b42487cca#diff-1cd097c1de92fff8c43bc33eb4f52405eb5396f9e8cc922a4502e4cad12e1f88).
Support for the tablist header and footer was added [here](https://github.com/PaperMC/Velocity/commit/5da085d82f9cd7a91a4b8d44f6dc94dc3383b173#diff-1cd097c1de92fff8c43bc33eb4f52405eb5396f9e8cc922a4502e4cad12e1f88).
Link to the original page: https://docs.papermc.io/velocity/dev/pitfalls#audience-operations-not-supported
Link to the page: …
=> Update audience operation support details in Velocity

package.json, patches/@docusaurus__plugin-content-docs@3.5.2.patch, patches/@docusaurus__utils@3.5.2.patch, pnpm-lock.yaml, tsconfig.json
This PR just update docusaurus to 3.5.2 and also migrate the devPackage for the tsconfig used by docusaurus.
the tsconfig currently used is for the v2 of docusaurus and not the v3.
=> chore: update docusaurus to 3.5.2 and migrate tsconfig for docusaurus 

docs/velocity/dev/api/plugin-messaging.mdx
as well as the warnings and updated example code, it also includes 
- more specific diagrams for each case
- fixed identifier checking, rather than by identity
- instanceof style cast.
=> set event result, and add warnings to velocity plugin messaging docs

.editorconfig, CONTRIBUTING.md, README.md, docs/paper/dev/getting-started/project-setup.mdx
Formatting needs to be double checked.
Currently the formatting in codeblocks is not consistent. On some pages it's 2 spaces and in other it's 4 spaces.
=> add maven dependency info

docs/paper/admin/reference/system-properties.md
This adds documentation for the `minecraft.api.session.host` and `minecraft.api.services.host` system properties.
=> Document session and services host properties

docs/misc/hangar-publishing.md
When I tried to build this for myself I saw that `HANGAR_API_TOKEN` was instead called `HANGAR_TOKEN` this fixes that.
=> Fix inconsistency within publish.yml

docs/paper/dev/api/scheduler.mdx
Fixes a small typo in the `BukkitRunnable` section of the Scheduler page, where it uses `task.cancel();` when it actually should be `this.cancel();` as mentioned.
=> Fix typo for BukkitRunnable page

config-specs/paper/paper-global.yml, config-specs/paper/vanilla/paper-global.yml, docs/paper/admin/misc/paper-bug-fixes.md
Linked to: https://github.com/PaperMC/Paper/pull/11670/
=> Remove string dupe exploit setting

docs/velocity/dev/api/event.mdx
Update event.mdx to remove deprecated velocity API usage.
=> Update velocity event.mdx

src/util/versionUtils.ts
Just a very quick fix to jmp pushing out an experimental version of userdev, which should not be suggested as the latest version in the docs rn.
> [!NOTE]
> It would make sense to filter out pre-release versions on the GitHub api side of things, but as the current beta release is marked as a full release, that is sadly not possible for this exact case
=> [Quickfix] Remove beta versions as possible latest userdev version

docs/paper/dev/getting-started/userdev.mdx
Regarding the lot of recent questions about userdev on **1.21.4**, this PR adds a warning so make people aware of the need for gradle 8.11.2 and the beta userdev releases.
=> [Quickfix] Add quick information about userdev 1.21.4 and beta versions

docs/paper/dev/getting-started/userdev.mdx, src/util/versionUtils.ts
This PR removes the filtering out of beta versions from the latest-version fetch in order to display the now pretty much stable beta builds, as they are required for 1.21.4 support and provide fixes for older versions as well.
Furthermore, I have added a reference to the Gradle wrapper page for updating your Gradle distribution and added a reference to the #build-tooling-help channel from our Discord server for people seeking further support.
=> fix: Update paperweight-userdev Gradle plugin reference

src/components/permission/PermissionSpec.tsx, src/components/permission/Permissions.tsx
Adds paper.antixray.bypass and paper.bypass-visibility.tab-completion
I added Permission sections to allow for easy having different prefixes. i didn't make it recursive though if we ever need really have that many permissions with common prefixes that are multiple layers deep then that shouldn't be too hard to change.
=> Add missing Permissions

docs/velocity/admin/reference/commands.md
Docs PR for PaperMc/Velocity#1427
=> Update velocity shutdown command (PaperMc/Velocity#1427)

config-specs/paper/paper-world-defaults.yml
This config option has some nasty consequences for survival and should be explained. I had some very weird problems after tuning this option (trying to save a server with ~500 players online from 1 TPS) and it was difficult to understand what was going on without a lot of trial and error. 
This clarification is based on my experience in #folia-help and should make it easier for server admins in the future to avoid degrading player experience unintentionally.
=> Explain paper-world-defaults.yml's tick-rate.container-update option better.

docs/paper/dev/api/data-component-api.mdx
Owen's PR is just meant as a base, so I suppose I will be PRing my changes to his branch
=> DataComponent PR fixup PR

docs/paper/dev/api/pdc.mdx
=> Document more pdc usages in the API

docs/velocity/admin/reference/system-properties.md
Add the [`VELOCITY_FORWARDING_SECRET`](https://github.com/PaperMC/Velocity/blob/d9f1016bd57d50f5052bb90222894adb40fd256c/proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java#L479) environment variable.
=> feat: add Velocity environment variables

config-specs/paper/paper-global.yml
This PR aims to add docs for a config option:
https://github.com/PaperMC/Paper/pull/12327
(I did not touch that "unsupported setting" at the bottom there, I guess IntelliJ wanted to take control)
=> paper-global.yml - add bypass for vanilla ride command player restriction

docs/paper/dev/getting-started/userdev.mdx
Close https://github.com/PaperMC/docs/issues/556 moving the mention of the gradle version to a block note for make more clear about the need of keep gradle updated.
=> feat: move userdev advise for gradle version to note block

docs/paper/dev/api/component-api/i18n.mdx
This pull request updates the Adventure Internationalization documentation to reflect recent changes in the API. 
The current examples use `TranslationRegistry`, which has been deprecated and is scheduled for removal starting in version 4.20.0. To ensure compatibility with future versions of the Adventure library, the examples have been updated to use `TranslationStore` instead.
For more details on the deprecation, refer to the official documentation: [TranslationRegistry](https://jd.advntr.dev/api/latest/net/kyori/adventure/translation/TranslationRegistry.html).
=> docs: update adventure internationalization examples

src/content/docs/paper/dev/getting-started/plugin-yml.mdx
if this is less clear, then any of these could instead be used
=> fix `notop` permission default value

src/content/docs/paper/dev/api/entity-api/entity-teleport.md
Currently in docs this point to the Player javadoc class and not the method.
=> fix: point to correct javadoc for lookAt jd in teleport

src/content/docs/paper/dev/api/scheduler.md
This PR fix two little things in the paper/dev/scheduler page
- Use HTML tag for things like `Thing<AnotherThing>` with URL for avoid large separators with the markdown format
- ,
=> style: cleanup for paper/dev/scheduler page

.github/actions/setup-node-pnpm/action.yml, .github/workflows/build-preview.yaml, .github/workflows/deploy.yaml, .github/workflows/format.yaml, .github/workflows/spellcheck.yaml, README.md, package.json
Related to https://github.com/PaperMC/docs/pull/573 this PR try to make more clear what node engine version need to use also improvement the github action by using compose for a few "duplicate" steps.
=> chore: use node 22 and github actions improvements

src/content/docs/velocity/admin/reference/system-properties.md
see https://github.com/PaperMC/Velocity/commit/ae312339a36d9c60232a275378cf264d41d4f7c9
May close https://github.com/PaperMC/Velocity/issues/1270
=> chore: update the velocity iouring system property

src/components/ConfigNode.astro
uses :target selector to highlight the hyperlinked option so it's easier to notice between all other options.
=> Highlight the config section the link points to

src/content/docs/folia/admin/reference/region-logic.md
Very minor spelling/grammar fix which bugged me when reading the folia docs
=> Fix typo in region-logic.md

src/content/docs/velocity/admin/reference/system-properties.md
Adds the system property added in velocity to allow skipping the validation of
uncompressed packets sizes. Not sure on the wording, however.
=> add prop for velocity packet threshold validation

src/components/ConfigNode.astro, src/components/Version.astro, src/components/overrides/PageFrame.astro, src/styles/custom.css
- makes some light mode grays lighter for better legibility of black text on gray backgrounds
- makes the config node highlight full width to not mess up indentation (+ accent color instead of gray so it's easier to see on light backgrounds)
- moves the scrolling area of the sidebar to not include the dropdown (no longer a sticky element)
=> chore: misc styling touch-ups

src/content/docs/misc/java-install.md
title. It's not needed for the rest of the instructions and may cause some unintended side effects.
=> Don't instruct debian users to install random upgrades

src/content/docs/folia/admin/reference/faq.md
Folia's disabled commands updated to match 1.21.6/7's disabled commands.
=> Update Folia disabled commands in Folia FAQ.

src/content/docs/paper/dev/api/command-api/basics/introduction.md, src/content/docs/paper/dev/api/command-api/misc/basic-command.md
- Improves the basic commands page by suggesting the simpler way of registering commands.
- Adds a tip aside in the introductory page to slightly advertise their use for people not wanting to jump into the hell that is Brigadier.
=> feat: Improve basic commands page

src/content/docs/velocity/admin/reference/system-properties.md
This system property was introduced in https://github.com/PaperMC/Velocity/pull/560 but was never documented.
=> feat: document mojang.sessionserver system property

src/content/docs/paper/dev/api/lifecycle/lifecycle.md
Grammar correction. Incorrect indefinite article.
=> Updated lifecycle.md - Grammar correction.

src/content/docs/velocity/dev/getting-started/pitfalls.md
Reflect changes from [Velocity#1422](https://github.com/PaperMC/Velocity/pull/1422).
Prequirement:
=> chore: update velocity's adventure ops docs

src/content/docs/paper/dev/api/dialogs.mdx
This PR improves the documentation for the dialog API example, as several issues were noticed after reading it. The PR includes the following fixes:
- Using UUID instead of PlayerCommonConnection
- Using ConcurrentHashMap, since events are triggered in different threads
- One-minute timeout to prevent the player connection from hanging indefinitely
- Manually closing the dialog using Audience#closeDialog, as the client sometimes doesn't do this if no button was pressed (e.g., in case of a timeout)
- All of this includes a bit of adherence to best practices ;)
=> chore: improve documentation for the Dialog API

src/content/docs/adventure/community-libraries.mdx
These links lead to a 404
Was also mentioned here but seems to have been forgotten: https://github.com/PaperMC/docs/pull/573#discussion_r2097747453
=> Fix community library links

src/content/docs/adventure/faq.md, src/content/docs/adventure/minimessage/format.mdx, src/content/docs/paper/dev/api/component-api/intro.md
This just replace the mentions for the Wiki RAW-JSON to the new article for avoid the unnecesary redirection.
=> fix: Use new Wiki Article for RAW-JSON/TextComponent
